### DISCUSSION TITLE
Add resource limits with ee command

### DISCUSSION THREAD

**Discussion by prionkor** [EasyEngine/easyengine#1771] [Feature Requests]
With docker compose file we can add resource limits to each container. 

```


deploy:
  resources:
    limits:
      cpus: '0.001'
      memory: 50M
    reservations:
      cpus: '0.0001'
      memory: 20M

```

https://docs.docker.com/compose/compose-file/compose-file-v3/#resources

Default behavior should be like we have now, but if anyone wants to add limits they can using `ee` command.
