### ISSUE TITLE
v4 Admin Tools Location

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#1013]
**Update**

- [ ] Use option 5 i.e. `/ee-admin` for all tools. No need to give an option to override.

URLs will look like:
- example.com/ee-admin/index.html
- example.com/ee-admin/pma
- example.com/ee-admin/mailhog
- example.com/ee-admin/adminer 
- example.com/ee-admin/webgrind
- example.com/ee-admin/redisadmin
- example.com/ee-admin/anonometer

____

EasyEngine provides tools like phpMyAdmin, adminer, redis-cache viewer etc.

Also, there is a plan to allow users to add more admin tools over the time.

Now we are in last round of v4 development, we need to finalize where we would like to put admin tools.

## Option 1 - Port 22222
For example.com site, example.com:22222 will load admin tools at sample URLs like: 

- example.com:22222/pma
- example.com:22222/mailcatcher

*Pros*
- Separate port so no conflict with any URL from example.com

*Cons*
- Additional network config when running behind Cloudflare. 
- On AWS and some platform manual opening/whitelisting of port 22222 required. Not sure if this is a negative point or should be looked upon as a "feature"/safety net.

## Option 2 - Single Subdomain for admin tools

For example.com site, eeadmin.example.com will load admin tools at sample URLs like: 

- eeadmin.example.com/pma
- eeadmin.example.com/mailcatcher

*Pros*
- No port-related network config issues

*Cons* 
- DNS level changes needed

## Option 3 - Separate Subdomain for admin tools

For example.com site, each admin tool will be loaded on separate domains like:

- pma.example.com
- mailcatcher.example.com

*Pros*
- No port-related network config issues

*Cons* 
- DNS level changes needed, especially wildcard DNS.
- A site name in WordPress multisite (in subdomain mode) can conflict with admin tool name/subdomain.

## Option 4 - Separate top-level dirs for each tool

For example.com site, admin tools will load at sample URLs: 

- example.com/pma
- example.com/mailcatcher

*Pros*
- Easy to set up.

*Cons*
- Conflict with a URL from the application. 

## Option 5 - Single top-level dirs for all tool (like `wp-admin`)

For example.com site, admin tools will load at sample URLs: 

- example.com/ee-admin/pma
- example.com/ee-admin/mailcatcher

*Pros*
- Easy to set up.

*Cons*
- Conflict with a URL from the application domain. But only one URL needs to be handled.

I am inclined towards option 5 and option 1 (in order of preference).

**Comment by Helmi** [comment]
For my personal usage I'd chose Option 2 or 5.

Option 2 for me would be kind of an "admin domain" that I point to my servers anyway and are part of the server naming like vx1.myserverdomain.com, vx2.myserverdomain.com etc. It would be a handy way for me to use this to reach the admin tools.

Definitely Option 5 would work too and could easily be setup to use this administrative (sub) domain too.

For Option 5 maybe provide the option on install to chose/change the default alias in case /ee or whatever the default will be will be needed for something else?

**Comment by rahul286** [comment]
@michacassola two reasons to propose `ee-admin`

1. It sounds like `wp-admin` <3
2. Is unlikely to clash with a real word term. Shorters versions like `ee` `ea` or even `eea` may have some meaning in some language somewhere. 

The problem is when clash happens, it will be on end users end. Imagine a write on blog pushing post with conflicting slug and they keep wondering why they cant see the post in front!

We will see if we can make it easy to change or configure slug. 

So far we are also inclined towards option 5.

**Comment by michacassola** [comment]
@rahul286 Ok, then ee-admin it is. And I think you dont need to include a slug configrator as ee-admin will very very rarely interfer with anyones URL wishes.

**Comment by rahul286** [comment]
@michacassola agree with you. Makes sense! :)

**Comment by mbtamuli** [comment]
Example section of docker-compose.yml, that is working with Traefik (#1036)
```
  mail:
    image: easyengine/mail
    restart: always
    command: ["-invite-jim=false"]
    labels:
      - "traefik.port=8025"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST};PathPrefixStrip:/ee-admin/mailhog/"
    networks:
      - site-network

  phpmyadmin:
    image: easyengine/phpmyadmin
    restart: always
    environment:
      - PMA_ABSOLUTE_URI=http://${VIRTUAL_HOST}/ee-admin/pma/
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST};PathPrefixStrip:/ee-admin/pma/"
    networks:
      - site-network
```

CC: @mrrobot47
