### ISSUE TITLE
[Feature] Add support for Newrelic

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/easyengine#1390]
To add support for Newrelic, I've created a PR to add the Dockerfiles for running the necessary Docker images. https://github.com/EasyEngine/dockerfiles/pull/78. 

_**Note:** For now, this feature needs to use locally built images for testing. After a PR for this issue is ready(which will in turn test the Docker Images) we'll merge this PR - https://github.com/EasyEngine/dockerfiles/pull/78_

To use the Docker images,
1. The Newrelic Daemon needs to run only using a volume.
```yaml
  global-newrelic-daemon:
    image: easyengine/newrelic-daemon:v4.0.0
    restart: always
    volumes:
      - "newrelic_sock:/run/newrelic"
```
2. The PHP service per site needs to be changed(just mentioning the fields needed to be added/changed for brevity)
```yaml
  php:
    image: easyengine/php7.0:v4.0.1
    volumes:
      - "newrelic_sock:/run/newrelic"
    environment:
      - NEWRELIC_APPNAME=${VIRTUAL_HOST}
      - NEWRELIC_LICENSE_KEY
```
