### ISSUE TITLE
Full custom docker compose setup

### ISSUE THREAD

**Issue by dhsathiya** [EasyEngine/easyengine#1699]
All the services defined in a separate user-defined docker-compose file should be integrated with the site. Ie, on site enable the specific compose file should also get a `up` command.

This way, users can run multiple customized setups including Headless and Decoupled.

- [ ] Create a generic template that can be used for custom-docker compose file.

If feasible, also add a generic flag for enable, restart, disable commands to do operate over the specific compose file.

Eg. adding a Node service to current site stack
```yml
version: '3.5'

services:

  node:
    image: node@sha256:fd86131ddf8e0faa8ba7a3e49b6bf571745946e663e4065f3bff0a07204c1dde
    command: bash -c "cd /var/www/htdocs/current/frontend && npm i && npm run build && npm run start"
    restart: always
    labels:
      - "io.easyengine.site=example.com"
    volumes:
      - "htdocs:/var/www"
    external_links:
      - services_global-nginx-proxy_1:example.com
    networks:
      site-network:
        aliases:
          - example.com_node
      global-backend-network:

volumes:                                                                                                                                                                                  
  htdocs:                                                                                                                                                                                 
    external:                                                                                                                                                                             
      name: wpplugincomparertgw_htdocs                                                                                                                                                    

networks:
  site-network:
    name: example.com
    labels:
     - "org.label-schema.vendor=EasyEngine"
     - "io.easyengine.site=example.com"
  global-frontend-network:
    external:
      name: ee-global-frontend-network
  global-backend-network:
    external:
      name: ee-global-backend-network
```

---

An alternate approach to support multiple custom-docker-files:
1. All customised docker-compose files can be defined in a directory under `/opt/easyengine/sites/example.com/user-docker-compose`.
2. On site enable/disable/restart all the files by default will get the docker-compose signal.
3. For enable/disable/restart a specific service add a separate flag which will have the file name specified and command will only run the operation for that specific docker-compose file. 

Eg, ee site restart --custom-compose=node-docker-compose.yml . This command will restart only the service defined in node-docker-compose.yml. Leaving rest of the services unaffected.

**Directory Structure**
```
.
├── app
├── config
├── custom-compose
│   ├── elastic-search-docker-compose.yml
│   ├── memcache-docker-compose.yml
│   └── node-docker-compose.yml
├── docker-compose-admin.yml
├── docker-compose-custom.yml
├── docker-compose.yml
├── logs
└── services
```
`ee site [enable/disable/restart]` - [enables/disables/restarts] docker-compose of site + all the docker-compose in custom-compose directory.
`ee site [enable/disable/restart] --custom-compose=memcache-docker-compose.yml` - [enables/disables/restarts] only the specified docker-compose file.
